<%inherit file="/test.mako"/>

<%def name="header()">
    ${head_content}
</%def>

<%def name="subtitle()">
    ${module}
</%def>

<%!
    from random import randint

    def rand_test():
        return randint(1,1000)
%>

<div class="appswell-demo" id="appswell-demo-index">

    <div class="controller_menu">
        <h3>menu</h3>
        <ul>
            ${menu}
        </ul>
    </div>

    <h2>${headline}</h2>

    <p>
        ${explanation}
    </p>
    <p>
        <%
            u = "http://code.google.com/p/appswell/source/browse/appspot/controllers/demo_controller.py#138"
        %>
        see the <a href="${u}">controller source code</a> for this action
        for a clearer picture.
    </p>

    <pre>random.randint(1,1000): ${rand_test()}*</pre>
    <h6>
        *This is one of the main reasons I prefer using mako templates.  The
        number above is generated by the python random library <em>within</em>
        the mako template itself.
    </h6>

    <br />
    <h5>return to <a href="/demo/templates">templates</a></h5>

</div>
